-- MySQL Script generated by MySQL Workbench
-- Sat May 12 14:55:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema desafio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema desafio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `desafio` DEFAULT CHARACTER SET utf8 ;
USE `desafio` ;

-- -----------------------------------------------------
-- Table `desafio`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desafio`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desafio`.`trilha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desafio`.`trilha` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(64) NOT NULL,
  `descricao` TEXT NOT NULL,
  `ativa` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desafio`.`fase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desafio`.`fase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_trilha` INT NULL,
  `titulo` VARCHAR(64) NOT NULL,
  `conteudo` TEXT NOT NULL,
  `ordem` INT NULL,
  `ativa` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fase_trilha_idx` (`id_trilha` ASC),
  CONSTRAINT `fk_fase_trilha`
    FOREIGN KEY (`id_trilha`)
    REFERENCES `desafio`.`trilha` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desafio`.`pergunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desafio`.`pergunta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(64) NOT NULL,
  `id_fase` INT NULL,
  `tipo` VARCHAR(24) NULL,
  `ativa` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_pergunta_fase1_idx` (`id_fase` ASC),
  CONSTRAINT `fk_pergunta_fase1`
    FOREIGN KEY (`id_fase`)
    REFERENCES `desafio`.`fase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desafio`.`opcao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `desafio`.`opcao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_pergunta` INT NULL,
  `titulo` TEXT NULL,
  `correta` TINYINT NULL,
  `ativa` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_opcao_pergunta1_idx` (`id_pergunta` ASC),
  CONSTRAINT `fk_opcao_pergunta1`
    FOREIGN KEY (`id_pergunta`)
    REFERENCES `desafio`.`pergunta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
